### PR TITLE
Improvements to Signature Checker

### PR DESCRIPTION
**Pull request by ghost**
These are not related to signature inference, but they are bug fixes and with them signature inference produces more meaningful results for the signature type system.

### CODE REVIEW

**Comment by pbsf** [comment]
@mernst2 , these are changes to the Signature Checker, not the Signature inference (which will be renamed to whole-program inference in the future). Isn't it better to merge this pull request with Checker Framework's master branch?

This is another reason why we need to rename this asap.

**Comment by mernst** [comment]
These bug fixes to the Signature Checker are needed in order to run tests
on the inference code. So the changes are necessary in this branch and the
PR was intentional. If I pushed them to the mainline, I would not be able
to run experiments (conveniently) until you rebased all the inference
changes on the mainline. I didn't want to force you to do that again, given
that the changes are not critical to most users. I do agree with you that
it is important to get the inference completed so we can merge it!

**Comment by pbsf** [comment]
@mernst, after merging this commit I found a bug when running the Checker Framework's javac on SigTest2.java with the Signature Checker ON, without the signature inference. 

I ran the following command:
`$CHECKERFRAMEWORK/checker/bin/javac -cp . -processor Signature -Awarns -AprintErrorStack SigTest2.java`

I'm attaching the log and SigTest2.java.

[sig-log.txt](https://github.com/pbsf/checker-framework/files/160608/sig-log.txt)

[SigTest2.txt](https://github.com/pbsf/checker-framework/files/161104/SigTest2.txt) (Github didn't allow me to upload a .java, so I renamed to .txt.)

**Comment by ghost** [comment]
The message is 

```
error: MultiGraphQualifierHierarchy could not determine GLB for @org.checkerframework.checker.signature.qual.SourceNameForNonArray and @org.checkerframework.checker.signature.qual.ClassGetSimpleName. Please ensure that the checker knows about all type qualifiers.
```

but qualifier SourceNameForNonArray no longer exists -- that was removed in commit 7e16c1792c105db6222c999bb7b7b3dfd1296e60.  This error probably means that an old `SourceNameForNonArray.class` file exists in your checkout and is being discovered by MultiGraphQualifierHierarchy.

I suggest that you clean your clone or create a new one, and that may eliminate the problem.  (I agree this is an obscure error!)

**Comment by ghost** [comment]
Another suggestion is to enable Travis CI builds for your clone.  Then you will see whether the Travis job, which always starts from a clean build, succeeds.  As a bonus, you will see before doing a merge whether my pull requests succeed.

You should be able to perform the steps at https://docs.travis-ci.com/user/getting-started/, but let me know if other steps are required so we can document them for other people working with their own fork.

**Pull request merged**
